### ISSUE TITLE
Error when using chirps estimate column

### ISSUE THREAD

**Issue by jkmusyoka** [IDEMSInternational/outfillingR#14]
@lilyclements 
When I use "chirps" as the "rainfall_estimate_column" in this function 
![image](https://github.com/user-attachments/assets/408f5930-7e97-4fa9-b361-c02d342d4b8e)
I get the following error 
![image](https://github.com/user-attachments/assets/2e7d60c9-e72d-422f-9749-d42697240a14)
Could you please check? Thanks

**Comment by lilyclements** [comment]
@jkmusyoka thanks for this. I believe this is now fixed after the changes in adding `fill_nearest` (PR https://github.com/IDEMSInternational/outfillingR/pull/16). If I am incorrect then let me know - it is working for me now using the zambia_data stored in the package (I assume this is the data you used)
