### ISSUE TITLE
Error when using era5 estimate column

### ISSUE THREAD

**Issue by jkmusyoka** [IDEMSInternational/outfillingR#15]
@lilyclements here is another error when I use the "era5" to infill the data. 
![image](https://github.com/user-attachments/assets/9893ecb5-b30d-497a-a401-85573c9a8220)
The error is generated by the following code 
![image](https://github.com/user-attachments/assets/b86b57f5-dc73-4dff-a0c3-f5493bb28440)

**Comment by lilyclements** [comment]
@jkmusyoka thanks for this. I believe this is now fixed after the changes in adding `fill_nearest` (PR #16). If I am incorrect then let me know - it is working for me now using the `zambia_data` stored in the package (I assume this is the data you used)
